eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
      hostname: localhost
      
      
microservice:
   payment-service:
     endpoints:
       endpoint:
         uri: http://PAYMENT-SERVICE/api/v1/payment/dopayment
   order-service:
     endpoints:
       endpoint:
         uri: http://ORDER-SERVICE/api/v1/order/bookorders
    admin-service:
     endpoints:
       endpoint:
         uri: http://ADMIN-SERVICE/api/v1/admin  
    user-service:
     endpoints:
       endpoint:
         uri: http://USER-SERVICE/api/v1/user 
    inventory-service:
     endpoints:
       endpoint:
         uri: http://INVENTORY-SERVICE/api/v1/product        
         
         
